services:
  - type: web
    name: ticket-classifier
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: HF_REPO_ID
        value: Tushar7012/ticket-classifier
      - key: PYTHON_VERSION
        value: 3.10.0
